# Generated by Django 3.2 on 2022-11-29 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_auto_20221113_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
